version: '3.8'

networks:
  laravel:
  user_rabbitmq:
    driver: bridge

services:
  user_nginx:
    image: nginx:stable-alpine
    container_name: user_nginx
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_php
      - user_mysql
    networks:
      - laravel

  user_rabbitmq:
    image: rabbitmq:3-management
    hostname: 'mabbit'
    container_name: rabbitmq_management
    environment:
      - RABBITMQ_DEFAULT_USER = ygkybebp
      - RABBITMQ_DEFAULT_PASS = Fglat0CpQ1T7M0BW82J8Eyln36cZWxoh
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./src:/var/lib/rabbitmq/mnesia/"
    restart: always
    networks:
      - user_rabbitmq

  user_mysql:
    image: mysql:8.0
    container_name: user_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: jvconsult
      MYSQL_USER: root
      MYSQL_PASSWORD: arthur
      MYSQL_ROOT_PASSWORD: arthur
      SERVICE_TAGS: dev
      SERVICE_NAME: user_mysql
    networks:
      - laravel
    volumes:
      - ./mysql:/var/lib/mysql

  user_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_php
    working_dir: /var/www
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    ports:
      - 9000:9000
    depends_on:
      - user_mysql
